name: Deploy to firebase

on:
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Deploy to Firebase Function
              uses: Winter-wub/deploy-firebase-functions@1.0.1

            - name: Deploy to Firebase Hosting
              uses: lowply/deploy-firebase@v0.0.4
